name: Publish to npmjs.org >> It's an event management react library.

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  quality:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ ubuntu-latest ]
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
      - name: Automated Version
        uses: phips28/gh-action-bump-version@v8.0.18
      - uses: actions/checkout@v1
      - name: Node setup ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}